name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3.5.3
    - name: Autenticação no DockerHub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PASS}}
    - name: Construção da imagem Docker
      uses: docker/build-push-action@v4.1.1
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          masilva2018/live-kube-news:${{github.run_number}}
          masilva2018/live-kube-news:latest
    
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    
    steps:
      - uses: actions/checkout@v3.5.3
      
      - name: Definindo context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
          
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          images:  masilva2018/live-kube-news:${{github.run_number}}
          manifests: |
            k8s/deplpoyment.yaml
            
